### ISSUE TITLE
debian 12 cross build openwrt version

### ISSUE THREAD

**Issue by carlsue** [transmission/libutp#14]
```
root@debian:/opt/Transmission/build# cmake --build .
[  4%] Built target deflate
[  8%] Built target event
[ 12%] Built target dht
[ 16%] Built target psl
[ 18%] Built target wildmat
[ 19%] Building CXX object third-party/libutp.bld/CMakeFiles/libutp.dir/utp_api.cpp.o
mipsel-openwrt-linux-g++: warning: environment variable 'STAGING_DIR' not defined
In file included from /opt/Transmission/third-party/libutp/utp_api.cpp:27:0:
/opt/Transmission/third-party/libutp/utp_internal.h:100:13: error: specialization of 'template<class _Tp> struct std::hash' in different namespace [-fpermissive]
 struct std::hash<UTPSocketKey>
             ^
In file included from /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/mipsel-openwrt-linux-uclibc/include/c++/5.5.0/bits/basic_string.h:5574:0,
                 from /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/mipsel-openwrt-linux-uclibc/include/c++/5.5.0/string:52,
                 from /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/mipsel-openwrt-linux-uclibc/include/c++/5.5.0/stdexcept:39,
                 from /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/mipsel-openwrt-linux-uclibc/include/c++/5.5.0/array:38,
                 from /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/mipsel-openwrt-linux-uclibc/include/c++/5.5.0/tuple:39,
                 from /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/mipsel-openwrt-linux-uclibc/include/c++/5.5.0/functional:55,
                 from /opt/Transmission/third-party/libutp/utp_internal.h:31,
                 from /opt/Transmission/third-party/libutp/utp_api.cpp:27:
/opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/mipsel-openwrt-linux-uclibc/include/c++/5.5.0/bits/functional_hash.h:58:12: error:   from definition of 'template<class _Tp> struct std::hash' [-fpermissive]
     struct hash;
            ^
In file included from /opt/Transmission/third-party/libutp/utp_api.cpp:27:0:
/opt/Transmission/third-party/libutp/utp_internal.h:130:46: warning: 'nodiscard' attribute directive ignored [-Wattributes]
  [[nodiscard]] auto contains(Key const& key) const {
                                              ^
/opt/Transmission/third-party/libutp/utp_internal.h:134:28: warning: 'nodiscard' attribute directive ignored [-Wattributes]
  [[nodiscard]] auto size() const {
                            ^
/opt/Transmission/third-party/libutp/utp_internal.h:138:46: warning: 'nodiscard' attribute directive ignored [-Wattributes]
  [[nodiscard]] Value* lookup(Key const& key) const {
                                              ^
gmake[2]: *** [third-party/libutp.bld/CMakeFiles/libutp.dir/build.make:76: third-party/libutp.bld/CMakeFiles/libutp.dir/utp_api.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:472: third-party/libutp.bld/CMakeFiles/libutp.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
root@debian:/opt/Transmission/build# file /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-gcc
/opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-gcc: symbolic link to mipsel-openwrt-linux-uclibc-gcc
root@debian:/opt/Transmission/build# file /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-g++
/opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-g++: symbolic link to mipsel-openwrt-linux-uclibc-g++
root@debian:/opt/Transmission/build#
```

**Comment by mikedld** [comment]
Your compiler (GCC 5.5?) appears to be too old to handle it. I've tested it with [Godbolt](https://godbolt.org/) and GCC 7.1 doesn't complain about this `std::hash` specialization while GCC 6.4 still does.

**Comment by carlsue** [comment]
> Your compiler (GCC 5.5?) appears to be too old to handle it. I've tested it with [Godbolt](https://godbolt.org/) and GCC 7.1 doesn't complain about this `std::hash` specialization while GCC 6.4 still does.
YES it's 5.5.0

root@ubuntu:/opt/Transmission# cmake -B build -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-gcc
-- Check for working C compiler: /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-g++
-- Check for working CXX compiler: /opt/PandoraBox-SDK/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CURL: /opt/PandoraBox-SDK/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/usr/lib/libcurl.so (found suitable version "7.68.0", minimum required is "7.28.0")  
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR: Found unsuitable version "1.0.2o", but required is at least "1.1.0" (found /opt/PandoraBox-SDK/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/usr/lib/libcrypto.so)
-- Found WolfSSL: /opt/PandoraBox-SDK/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/usr/lib/libwolfssl.so (found suitable version "3.9.6", minimum required is "3.4") 
-- Checking for modules 'gtkmm-4.0>=4.11.1;glibmm-2.68>=2.60.0;giomm-2.68>=2.26.0'
--   No package 'gtkmm-4.0' found
--   No package 'glibmm-2.68' found
--   No package 'giomm-2.68' found
-- Checking for modules 'gtkmm-3.0>=3.24.0;glibmm-2.4>=2.60.0;giomm-2.4>=2.26.0'
--   No package 'gtkmm-3.0' found
--   No package 'glibmm-2.4' found
--   No package 'giomm-2.4' found
